### ISSUE TITLE
Return Promise on `saveToDisk`

### ISSUE THREAD

**Issue by moeriki** [zaaack/keyv-file#1]
Would it be possible to update `saveToDisk` to return the Promise.

I'm using `keyv` / `keyv-file` in a script and I need to flush before exit.

Right now I have to do this.

```js
doingMyThing()
  .then(() => {
    store.saveToDisk();
    return new Promise((resolve) => setTimeout(resolve, 50));
  })
```

Cheers.

**Comment by zaaack** [comment]
@Moeriki Just published a new version, feel free to reopen this issue if your problem is not solved.

**Comment by moeriki** [comment]
Works like a charm. Thanks!
