### ISSUE TITLE
How to iterate over all elements

### ISSUE THREAD

**Issue by Kikobeats** [zaaack/keyv-file#2]
Hello,

Reading Keyv, I see all storages follow Map API.

In my user case, I'm using keyv-file and I need to iterate over all values. Ideally, using [Map.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach).

After review the code I see method is not implemented. I can do it, but any tip for do that?

Load all the file in memory could be bloat. A good solution could create a [readable msgpack5 stream](https://npms.io/search?q=stream+msgpack) and consume the data.

What do you think?

**Comment by zaaack** [comment]
Just published a new version v0.1.7, add a `.keys()` method to get all keys. 

keyv-file is a simple adapter of [keyv](https://github.com/lukechilds/keyv), which means not all APIs of Map need to be implemented, only those keyv required.

If we implement all methods in msgpack5 stream, this would slow the get method, and I don't have any experiences of implementing an index system. Fortunately it is just a simple in-memory cache library with lightweight fs backup support, and is very easy to switch to other adapters like keyv-redis, keyv-postgres, etc.

But I think is ok to have a stream-based API if we provide it as a option, PR's are welcome!

**Comment by Kikobeats** [comment]
oh thanks! I think that for now is ok 😄
