### ISSUE TITLE
new KeyvFile() now requires every option to be specified, but previously the options were optional

### ISSUE THREAD

**Issue by msheakoski** [zaaack/keyv-file#23]
In commit 00dd695 a change was introduced that made every property of Options required:

https://github.com/zaaack/keyv-file/blob/ee03b45edcd5e7843a3f9dd1767d1e656cedbfee/index.ts#L8-L15
https://github.com/zaaack/keyv-file/blob/ee03b45edcd5e7843a3f9dd1767d1e656cedbfee/index.ts#L37

Since every property has a default value, the Options interface should be wrapped in a `Partial<>`:

```typescript
constructor(options?: Partial<Options>)
```

or have the interface properties declared as optional:

```typescript
 export interface Options { 
     deserialize?: (val: any) => any; 
     dialect?: string 
     expiredCheckDelay?: number; // milliseconds 
     filename?: string; 
     serialize?: (val: any) => any; 
     writeDelay?: number; // milliseconds 
 }
```

**Comment by zaaack** [comment]
fixed
